Repository Sparta-Triple/CultureTicket, pull requests merged in 2025-01, with the labels that each got.

#11 [Feat]: User 생성(회원가입), 로그인 기능 구현 #7
  com.culture-ticket.client.gateway/build.gradle
  com.culture-ticket.client.gateway/src/main/java/com/culture_ticket/client/gateway/filter/CustomPostFilter.java
  com.culture-ticket.client.gateway/src/main/java/com/culture_ticket/client/gateway/filter/CustomPreFilter.java
  com.culture-ticket.client.gateway/src/main/java/com/culture_ticket/client/gateway/filter/LocalJwtAuthenticationFilter.java
  com.culture-ticket.client.gateway/src/main/resources/application.properties
  com.culture-ticket.client.gateway/src/main/resources/application.yml
  com.culture-ticket.client.user/build.gradle
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/UserApplication.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/dto/request/LoginRequestDto.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/dto/request/SignupRequestDto.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/dto/request/UserInfoUpdateRequestDto.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/dto/response/UserInfoResponseDto.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/security/UserDetailsImpl.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/security/jwt/JwtAuthenticationFilter.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/security/jwt/JwtAuthorizationFilter.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/security/jwt/JwtUtil.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/service/UserDetailsServiceImpl.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/service/UserService.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/common/CustomException.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/common/ErrorType.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/common/ResponseDataDto.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/common/ResponseMessageDto.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/common/ResponseStatus.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/domain/model/BaseEntity.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/domain/model/Role.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/domain/model/User.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/domain/repository/UserRepository.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/infrastructure/configuration/SecurityConfig.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/presentation/controller/UserController.java
  com.culture-ticket.client.user/src/main/resources/application.properties
  com.culture-ticket.client.user/src/main/resources/application.yml
  com.culture-ticket.client.user/src/test/java/com/culture_ticket/client/user/UserApplicationTests.java
  com.culture-ticket.server/src/main/java/com/culture_ticket/server/ServerApplication.java
  com.culture-ticket.server/src/main/resources/application.properties
  com.culture-ticket.server/src/main/resources/application.yml
Labels: feat

#27 Feat/#15 TimeTable CRUD, Search, Restore 기능 구현
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/requestDto/TimeTableCreateRequestDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/requestDto/TimeTableSearchRequestDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/responseDto/TimeTableSearchResponseDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/SeatService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/TimeTableService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/ErrorType.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/ResponseStatus.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/util/RoleValidator.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/model/BaseEntity.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/model/Performance.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/model/TimeTable.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/model/TimeTableStatus.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/repository/TimeTableRepository.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/repository/TimeTableRepositoryCustom.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/repository/TimeTableRepositoryCustomImpl.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/PerformanceController.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/TimeTableController.java
  com.culture-ticket.client.performance/src/test/java/com/culture_ticket/client/performance/PerformanceApplicationTests.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/application/dto/request/SignupRequestDto.java
Labels: feat

#30 [Feat]: Seat CRUD, Restore 기능 구현
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/requestDto/PerformanceCreateRequestDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/requestDto/PerformanceDomainCreateRequestDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/requestDto/SeatCreateRequestDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/requestDto/TimeTableCreateRequestDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/requestDto/UpdateSeatPriceRequestDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/responseDto/SeatInfoResponseDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/PerformanceService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/SeatService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/TimeTableService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/ResponseStatus.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/model/Seat.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/model/SeatStatus.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/model/TimeTable.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/repository/SeatRepository.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/repository/TimeTableRepositoryCustomImpl.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/service/PerformanceDomainService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/PerformanceController.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/SeatController.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/TimeTableController.java
Labels: feat

#32 [Refactor]: 공연 도메인 생성 시 타임 테이블을 리스트로 생성하도록 변경
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/requestDto/PerformanceDomainCreateRequestDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/SeatService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/TimeTableService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/model/TimeTable.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/domain/service/PerformanceDomainService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/SeatController.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/TimeTableController.java
Labels: feat

#19 Feat/#5 reservation 예매 기능
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/dto/responseDto/SeatInfoResponseDto.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/SeatService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/TimeTableService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/ErrorType.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/ResponseStatus.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/SeatController.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/TimeTableController.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/TimeTableInfoResponseDto.java
  com.culture-ticket.client.performance/src/main/resources/application.yml
  com.culture-ticket.client.reservation-payment/.gitignore
  com.culture-ticket.client.reservation-payment/HELP.md
  com.culture-ticket.client.reservation-payment/build.gradle
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/application/dto/responseDto/RefundPriceResponseDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/application/dto/responseDto/ReservationResponseDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/application/service/PaymentService.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/application/service/ReservationService.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/common/ErrorType.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/common/ResponseMessageDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/common/ResponseStatus.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/common/util/PageableUtil.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/common/util/RoleValidator.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/domain/model/Payment.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/domain/model/Reservation.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/domain/model/ReservationStatus.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/domain/model/SeatPayment.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/domain/repository/ReservationRepository.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/client/PerformanceClient.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/client/SeatClient.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/client/TicketClient.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/client/UserClient.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/configuration/QueryDslConfig.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/dto/FeignClientResponseDataDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/dto/FeignClientResponseMessageDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/dto/PerformanceResponseDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/dto/SeatResponseDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/dto/TicketRequestDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/dto/TimeTableResponseDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/dto/UserResponseDto.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/repository/ReservationRepositoryCustom.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/infrastructure/repository/ReservationRepositoryCustomImpl.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/presentation/controller/PaymentController.java
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/presentation/controller/ReservationController.java
  com.culture-ticket.client.reservation-payment/src/main/resources/application.yml
  com.culture-ticket.client.reservation-payment/src/test/java/com/culture_ticket/client/reservation_payment/ReservationPaymentApplicationTests.java
  com.culture-ticket.client.ticket/src/main/java/com/culture_ticket/client/ticket/TicketApplication.java
  com.culture-ticket.client.ticket/src/main/java/com/culture_ticket/client/ticket/application/service/TicketService.java
  com.culture-ticket.client.ticket/src/main/java/com/culture_ticket/client/ticket/domain/model/Ticket.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/infrastructure/configuration/SecurityConfig.java
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/presentation/controller/UserController.java
  com.culture-ticket.client.user/src/main/resources/application.yml
Labels: feat

#45 쿠폰 발급 기능 구현
  com.culture-ticket.client.coupon/build.gradle
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/CouponApplication.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/application/dto/request/CouponCreateRequestDto.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/application/dto/response/CouponResponseDto.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/application/service/CouponDecreaseService.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/application/service/CouponIssueService.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/application/service/CouponService.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/common/ErrorType.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/common/ResponseStatus.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/common/util/RoleValidator.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/domain/medel/Coupon.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/domain/model/BaseEntity.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/domain/model/Coupon.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/domain/model/CouponUser.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/domain/repository/CouponRepository.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/domain/repository/CouponUserRepository.java
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/presentation/controller/CouponController.java
  com.culture-ticket.client.coupon/src/test/java/com/culture_ticket/client/coupon/CouponDecreaseLockTest.java
  com.culture-ticket.client.gateway/src/main/resources/application.yml
  com.culture-ticket.client.reservation-payment/src/main/java/com/culture_ticket/client/reservation_payment/application/service/PaymentService.java
  com.culture-ticket.client.ticket/src/main/java/com/culture_ticket/client/ticket/application/service/TicketService.java
Labels: feat

#47 Redis를 활용한 실시간 랭킹 기능 구현
  com.culture-ticket.client.coupon/src/main/java/com/culture_ticket/client/coupon/infrastructure/aop/DistributeLockAop.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/PerformanceApplication.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/PerformanceService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/ResponseStatus.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/util/RedisKeyHelper.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/util/RedisKeyType.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/common/util/ScheduledTaskExecutor.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/infrastructure/config/CacheConfig.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/presentation/controller/PerformanceController.java
Labels: feat

#51 WaitingQueueEntity 생성 안되던 오류 수정
  com.culture-ticket.client.queue/src/main/java/com/culture_ticket/client/queue/domain/medel/WaitingQueueEntity.java
Labels: fix

#53 [Docs]: Swagger api docs 설정 추가
  com.culture-ticket.client.coupon/build.gradle
  com.culture-ticket.client.coupon/src/main/resources/application.yml
  com.culture-ticket.client.gateway/build.gradle
  com.culture-ticket.client.gateway/src/main/java/com/culture_ticket/client/gateway/filter/LocalJwtAuthenticationFilter.java
  com.culture-ticket.client.gateway/src/main/resources/application.yml
  com.culture-ticket.client.performance/build.gradle
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/application/service/PerformanceService.java
  com.culture-ticket.client.performance/src/main/java/com/culture_ticket/client/performance/infrastructure/config/CacheConfig.java
  com.culture-ticket.client.performance/src/main/resources/application.yml
  com.culture-ticket.client.queue/build.gradle
  com.culture-ticket.client.queue/src/main/java/com/culture_ticket/client/queue/infrastructure/configuration/RedissonConfig.java
  com.culture-ticket.client.queue/src/main/resources/application.yml
  com.culture-ticket.client.reservation-payment/build.gradle
  com.culture-ticket.client.reservation-payment/src/main/resources/application.yml
  com.culture-ticket.client.ticket/build.gradle
  com.culture-ticket.client.ticket/src/main/resources/application.yml
  com.culture-ticket.client.user/build.gradle
  com.culture-ticket.client.user/src/main/java/com/culture_ticket/client/user/infrastructure/configuration/SecurityConfig.java
  com.culture-ticket.client.user/src/main/resources/application.yml
Labels: docs
